"""E2E scenario 7: unified five-sheet .xlsx import (rework 6.2).

Full user path through the single «Импорт из .xlsx…» action: browse (file
dialog stubbed) → pre-analysis (the two deliberately broken fixture rows are
shown as sheet/row/reason BEFORE anything is written) → confirm → report
panel → events appear on the scale and the imported links are visible in the
event dialog. The second test restarts the application (shutdown → start the
same game file) and proves the import's commit persisted the whole world:
entities, M2M links, ghost target and auto-created event types.

The fixture is the five-sheet sample regenerated by
tests/application/test_xlsx_import_service.py (drift-guarded there); its
deliberate problem rows live at «События» строка 4 and «Персонажи» строка 6.
"""
from __future__ import annotations

from pathlib import Path

from app.presentation.views.event_dialog import EventDialog
from app.presentation.views.xlsx_import_dialog import XlsxImportDialog

from tests.presentation.qml_helpers import (
    click_item,
    find_item,
    find_items,
    island_row_texts,
    walk_items,
)
from tests.ui import helpers, timeline_probe
from tests.ui.conftest import query_db

FIXTURE_XLSX = Path(__file__).resolve().parent.parent / "fixtures" / "import_sample.xlsx"

# Row problems the fixture carries on purpose (mirrors EXPECTED_SKIPS of the
# acceptance suite — sheet, Excel row number, reason shown to the user).
SKIPS = [
    ("События", 4, "дата начала: значение «31.12.2025» не является датой"),
    ("Персонажи", 6, "рейтинг 9 вне диапазона 1..5"),
]


def _import_dialogs(window):
    return [d for d in window.findChildren(XlsxImportDialog) if d.isVisible()]


def _tab_names(tab) -> set[str]:
    return {
        tab.list_widget.item(i).text()
        for i in range(tab.list_widget.count())
    }


async def _import_fixture_through_dialog(window, file_dialogs, wait_for):
    """browse → analyze → confirm; the dialog is back in ``done`` state."""
    file_dialogs["open"] = str(FIXTURE_XLSX)
    window.import_xlsx_action.trigger()
    await wait_for(lambda: _import_dialogs(window))
    dialog = _import_dialogs(window)[0]

    click_item(dialog.quick, find_item(dialog.quick, "browseButton"))
    assert dialog.path_edit.text() == str(FIXTURE_XLSX)

    # primary button #1: «Проверить…» → pre-analysis
    dialog.import_btn.click()
    await wait_for(lambda: dialog.vm.state == "problems")
    return dialog


async def test_unified_import_shows_problems_report_and_links(
    app, file_dialogs, wait_for
):
    """Pre-analysis pool before any write → import with skips → report with
    counts/decisions → events on the scale → links visible in the event
    dialog (spec «Пред-анализ», «Отчёт с пропусками», «Ссылка на строку
    другого листа»)."""
    application, window = app
    db_path = application._db_path

    dialog = await _import_fixture_through_dialog(window, file_dialogs, wait_for)

    # The pool is displayed with sheet/row/reason…
    await wait_for(lambda: len(find_items(dialog.quick, "issueRow")) == 2)
    dialog.quick.grab()
    assert island_row_texts(dialog.quick, "issueRow", "issueSheetText") == [
        "лист «События»", "лист «Персонажи»",
    ]
    assert island_row_texts(dialog.quick, "issueRow", "issueRowNumberText") == [
        "строка 4", "строка 6",
    ]
    assert island_row_texts(dialog.quick, "issueRow", "issueReasonText") == [
        reason for _sheet, _row, reason in SKIPS
    ]
    # …nothing was written while the user decides (spec «до начала записи»)
    assert query_db(db_path, "SELECT COUNT(*) FROM events")[0][0] == 0
    # row-only problems do not block: the button means «Импортировать»
    assert dialog.vm.hasFatal is False and dialog.vm.canImport is True
    assert dialog.import_btn.text() == "Импортировать"

    # primary button #2: confirm → one-transaction apply → report
    dialog.import_btn.click()
    await wait_for(lambda: dialog.vm.state == "done")
    report = dialog.vm.report
    # 10 file rows + the ghost «Амулет вдовы»; two broken rows skipped
    assert report["created"] == 11 and report["updated"] == 0
    assert report["links"] == 17
    assert [
        (s["sheet"], s["row"], s["reason"]) for s in report["skipped"]
    ] == SKIPS
    # two auto event types («Война», «Поход») + the auto-created ghost item
    assert len(report["decisions"]) == 3 and report["warnings"] == []

    await wait_for(lambda: len(
        [i for i in walk_items(dialog.quick.rootObject())
         if i.objectName() == "reportSkippedRowText"]
    ) == 2)
    dialog.quick.grab()
    skipped_texts = [
        i.property("text") for i in walk_items(dialog.quick.rootObject())
        if i.objectName() == "reportSkippedRowText"
    ]
    assert all("лист «" in t for t in skipped_texts)
    assert any("Амулет вдовы" in t for t in [
        i.property("text") for i in walk_items(dialog.quick.rootObject())
        if i.objectName() == "reportDecisionText"
    ])

    # Both valid events are on the scale (and nothing else — the skipped
    # «Пир в ратуше» never reached the DB).
    names = [e.name for e in timeline_probe.events(window)]
    assert len(names) == 2  # nothing else landed on the scale
    assert set(names) == {"Поход каравана на восток", "Взятие Штурмграда"}

    # Links from the file's «Связь …» columns are visible in the event dialog.
    helpers.double_click_timeline_event(window, "Взятие Штурмграда")
    await wait_for(lambda: [d for d in window.findChildren(EventDialog) if d.isVisible()])
    event_dialog = next(d for d in window.findChildren(EventDialog) if d.isVisible())
    assert _tab_names(event_dialog.char_tab) == {"Иван Ковач", "Марта", "Старый Кузнец"}
    assert _tab_names(event_dialog.org_tab) == {"Гильдия копья"}
    assert _tab_names(event_dialog.item_tab) == {"Штурмовой щит", "Амулет вдовы"}
    assert _tab_names(event_dialog.loc_tab) == {"Штурмград"}
    # the auto-created event type reached the world's type selector
    assert event_dialog.type_combo.findText("Война") >= 0


async def test_analysis_crash_shows_reason_in_the_problem_list(
    app, file_dialogs, wait_for, monkeypatch
):
    """Аварийный сбой чтения (не штатные фатальные ошибки плана) не роняет
    приложение: причина попадает в список проблем диалога."""
    application, window = app

    async def boom(path, session=None):
        raise RuntimeError("диск отвалился")
    monkeypatch.setattr(application._wiring._xlsx_import, "analyze_file", boom)

    file_dialogs["open"] = str(FIXTURE_XLSX)
    window.import_xlsx_action.trigger()
    await wait_for(lambda: _import_dialogs(window))
    dialog = _import_dialogs(window)[0]
    dialog.path_edit.setText(str(FIXTURE_XLSX))
    dialog.import_btn.click()  # «Проверить…»
    await wait_for(lambda: dialog.vm.state == "problems" and dialog.vm.hasFatal)
    assert "диск отвалился" in dialog.vm.analysisIssues[0]["reason"]


async def test_confirm_without_analyzed_plan_applies_nothing(
    app, wait_for, monkeypatch
):
    """Сигнал подтверждения до анализа (плана нет) — безопасный no-op:
    никакого применения, никакого падения."""
    import asyncio

    application, window = app

    async def spy(plan, session, progress_callback=None):
        raise AssertionError("apply_plan не должен вызываться без плана")
    monkeypatch.setattr(application._wiring._xlsx_import, "apply_plan", spy)

    window.import_xlsx_action.trigger()
    await wait_for(lambda: _import_dialogs(window))
    dialog = _import_dialogs(window)[0]
    dialog.confirm_import.emit()
    await asyncio.sleep(0.1)  # дать spawned-задаче дойти до выхода
    assert dialog.vm.state == "idle"


async def test_apply_crash_shows_reason_in_the_problem_list(
    app, file_dialogs, wait_for, monkeypatch
):
    """Сбой применения после коммита-отката (design D6): причина — в список
    проблем диалога, состояние — снова «с проблемами» с фаталом."""
    application, window = app
    dialog = await _import_fixture_through_dialog(window, file_dialogs, wait_for)

    async def boom(plan, session, progress_callback=None):
        raise RuntimeError("технический сбой прохода 2")
    monkeypatch.setattr(application._wiring._xlsx_import, "apply_plan", boom)

    dialog.import_btn.click()  # «Импортировать»
    await wait_for(lambda: dialog.vm.state == "problems" and dialog.vm.hasFatal)
    assert "сбой прохода 2" in dialog.vm.analysisIssues[0]["reason"]


async def test_imported_world_persists_after_app_restart(app, file_dialogs, wait_for):
    """Spec «Данные сохраняются сразу»: import → explicit restart (shutdown →
    start on the same game file) → entities, links, ghost and types in the
    freshly opened game."""
    application, window = app
    db_path = application._db_path

    dialog = await _import_fixture_through_dialog(window, file_dialogs, wait_for)
    dialog.import_btn.click()  # «Импортировать»
    await wait_for(lambda: dialog.vm.state == "done")
    dialog.import_btn.click()  # «Закрыть»
    await wait_for(lambda: not dialog.isVisible())

    # Real restart: the game DB file is reopened through a brand-new engine.
    await application.shutdown()
    window2 = await application.start(str(db_path))
    try:
        names = [e.name for e in timeline_probe.events(window2)]
        assert len(names) == 2  # exactly the imported events, no leftovers
        assert set(names) == {"Поход каравана на восток", "Взятие Штурмграда"}

        assert query_db(db_path, "SELECT COUNT(*) FROM characters")[0][0] == 3
        assert query_db(db_path, "SELECT COUNT(*) FROM locations")[0][0] == 2
        assert query_db(db_path, "SELECT COUNT(*) FROM organizations")[0][0] == 1
        # 2 file items + the ghost «Амулет вдовы» with its referral-date span
        assert query_db(
            db_path,
            "SELECT start_date, end_date FROM items WHERE name = 'Амулет вдовы'",
        ) == [("1200-05-01", "1203-01-20")]
        # six NRI defaults + the two auto-created types
        assert query_db(db_path, "SELECT COUNT(*) FROM event_types")[0][0] == 8
        assert {
            name for (name,) in query_db(
                db_path, "SELECT name FROM event_types WHERE name IN ('Война','Поход')"
            )
        } == {"Война", "Поход"}
        # every link the report counted is in the file's associations
        assert query_db(db_path,
                        "SELECT COUNT(*) FROM event_character")[0][0] == 5
        assert query_db(db_path,
                        "SELECT COUNT(*) FROM event_item")[0][0] == 4
        assert query_db(db_path,
                        "SELECT COUNT(*) FROM event_location")[0][0] == 2
        assert query_db(db_path,
                        "SELECT COUNT(*) FROM event_organization")[0][0] == 1
        # the skipped rows stayed out of the committed world
        assert query_db(
            db_path, "SELECT COUNT(*) FROM events WHERE name = 'Пир в ратуше'"
        ) == [(0,)]
        assert query_db(
            db_path, "SELECT COUNT(*) FROM characters WHERE name = 'Гоблин-наёмник'"
        ) == [(0,)]
    finally:
        window.close()  # no-op for the already closed pre-restart window
        await application.shutdown()
