"""Acceptance suite for the unified five-sheet import (task 6.1, rework-xlsx-import).

The committed binary ``tests/fixtures/import_sample.xlsx`` is generated by
:func:`build_import_sample_workbook` below — the same reproducible pattern as
the group-5 template tests: headers come from the schema registry (never
hand-typed), the data is ``FIXTURE_ROWS``. The first tests pin the committed
fixture against the generator cell-for-cell, the rest run it through the NEW
flow as the acceptance layer over the unit-level plan/apply suites:

* pre-analysis — no fatals/warnings, the deliberate problem rows surface as
  planned skips (sheet + Excel row number + reason), the in-file merge of two
  «Старый Кузнец» rows, the ghost «Амулет вдовы» with min-start/max-end dates
  of its two referring events, and the upsert plan against a pre-seeded DB;
* apply — created/updated/links counts, upsert semantics (an empty cell never
  erases a stored value), link edges installed over every involved M2M table,
  ghost + auto event types with their report decisions, and a re-import that
  creates/links nothing a second time;
* transaction — exactly one commit on success, full rollback of an injected
  pass-2 failure (the pre-import DB state survives untouched).

Row numbers below count the Excel rows of each sheet (header row = 1); the
generator emits every sheet's rows in ``FIXTURE_ROWS`` order.
"""
from __future__ import annotations

from datetime import date, datetime
from pathlib import Path

import pytest
from openpyxl import Workbook, load_workbook
from sqlalchemy import func, select

from app.application.services import xlsx_schema
from app.application.services.xlsx_import_service import (
    LINK_TO_FILE,
    LINK_TO_GHOST,
    XlsxImportService,
)
from app.domain import game_calendar
from app.domain.date_era import era_key
from app.domain.game_calendar import MonthDay
from app.infrastructure.db.uow import GameSessionUoW
from app.infrastructure.db import models
from app.infrastructure.db.models import (
    CharacterModel,
    DescriptionModel,
    EventModel,
    EventTypeModel,
    ItemModel,
    LocationModel,
    OrganizationModel,
)
from app.application.services.xlsx_template import (
    template_headers as registry_headers,
    template_row_values as registry_row_values,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "import_sample.xlsx"

# The deliberate contents (each row is keyed by column key / link target
# type, exactly as the template generator consumes them):
#
# * События строка 4 — broken start date «31.12.2025» → planned skip;
# * Персонажи строка 6 — rating 9 → planned skip;
# * Персонажи строки 4–5 — «Старый Кузнец» twice: in-file merge (later
#   non-empty overrides, links accumulate, empty cells do not erase);
# * every link column carries `;` lists with cross-sheet references in BOTH
#   directions (the event→character edges repeat from the character sheets);
# * «Амулет вдовы» is referenced by two events but exists nowhere → ghost
#   with the min-start/max-end span of its referring rows;
# * «Гильдия копья» and the type «война» match a pre-seeded DB by
#   lower(name)/lower(type) → upsert + type-reuse (the row leaves
#   `Предыстория`/`Дата конца` empty on purpose — acceptance checks that the
#   seeded values survive).
FIXTURE_ROWS: dict[str, list[dict[str, object]]] = {
    "event": [
        {
            "name": "Взятие Штурмграда", "start_date": date(1200, 5, 1),
            "end_date": "1200-09-15",
            "characteristics": "Осада длилась три недели",
            "backstory": "Город пал после разрушения стены",
            "event_type": "Война",
            "character": "Иван Ковач; Марта",
            "organization": "Гильдия копья",
            "item": "Штурмовой щит; Амулет вдовы",
            "location": "Штурмград",
        },
        {
            "name": "Поход каравана на восток", "start_date": "1202-06-10",
            "end_date": "1203-01-20",
            "characteristics": "Тридцать верблюдов и охрана",
            "event_type": "Поход",
            "character": "Иван Ковач",
            "item": "Карта востока; Амулет вдовы",
            "location": "Восточный тракт",
        },
        {  # строка 4: битая дата начала → planned skip
            "name": "Пир в ратуше", "start_date": "31.12.2025",
        },
    ],
    "character": [
        {
            "name": "Иван Ковач", "start_date": date(1180, 3, 1),
            "characteristics": "Городской кузнец",
            "rating": 4, "personality": "Упрямый",
            "tasks": "Сковать парадные доспехи",
            "event": "Взятие Штурмграда; Поход каравана на восток",
            "item": "Карта востока",
            "location": "Штурмград",
        },
        {
            "name": "Марта", "start_date": "1185-07-20",
            "characteristics": "Предприимчивая торговка",
            "event": "Взятие Штурмграда",
            "location": "Штурмград",
        },
        {  # «Старый Кузнец» — первая строка слияния
            "name": "Старый Кузнец", "start_date": "1160-01-01",
            "characteristics": "Молчалив, знает все ходы",
            "rating": 3,
            "event": "Взятие Штурмграда",
        },
        {  # «Старый Кузнец» — поздняя строка: заполненные поля перекрывают,
           # пустые не затирают, связи копятся
            "name": "Старый Кузнец", "start_date": "1161-02-02",
            "backstory": "Бывший капитан городской стражи",
            "event": "Поход каравана на восток",
        },
        {  # строка 6: рейтинг вне диапазона → planned skip
            "name": "Гоблин-наёмник", "start_date": "1201-01-01",
            "rating": 9,
        },
    ],
    "location": [
        {
            "name": "Штурмград", "start_date": "1100-01-01",
            "characteristics": "Обнесённая стеной крепость",
            "event": "Взятие Штурмграда",
            "character": "Иван Ковач; Марта",
        },
        {
            "name": "Восточный тракт", "start_date": "1100-01-01",
            "characteristics": "Пыльный путь к восточным рынкам",
            "event": "Поход каравана на восток",
        },
    ],
    "organization": [
        {
            "name": "Гильдия копья", "start_date": "1150-01-01",
            "characteristics": "Наёмники и ремесленники старого города",
            "event": "Взятие Штурмграда",
            "character": "Иван Ковач",
        },
    ],
    "item": [
        {
            "name": "Штурмовой щит", "start_date": "1195-01-01",
            "characteristics": "Калёный щит с клёпаным краем",
            "event": "Взятие Штурмграда",
            "character": "Иван Ковач",
        },
        {
            "name": "Карта востока", "start_date": "1201-01-01",
            "characteristics": "Выцветшая купеческая карта",
            "event": "Поход каравана на восток",
            "character": "Иван Ковач",
        },
    ],
}

# The two deliberate broken rows (spec «Пред-анализ файла до импорта»): with
# the generator-emitted layout they sit at these Excel row numbers.
EXPECTED_SKIPS = [
    ("События", 4, "дата начала: значение «31.12.2025» не является датой"),
    ("Персонажи", 6, "рейтинг 9 вне диапазона 1..5"),
]


def build_import_sample_workbook() -> Workbook:
    """Regenerate the sample workbook from the registry + FIXTURE_ROWS."""
    wb = Workbook()
    wb.remove(wb.active)
    for sheet in xlsx_schema.all_sheets():
        ws = wb.create_sheet(sheet.sheet_name)
        ws.append(registry_headers(sheet))
        for row in FIXTURE_ROWS[sheet.entity_type]:
            ws.append(registry_row_values(sheet, row))
    return wb


def _sheet_values(wb: Workbook, title: str) -> list[list[object]]:
    """Cell values of one sheet with datetimes normalized to dates."""
    rows = []
    for raw in wb[title].iter_rows(values_only=True):
        rows.append([
            value.date() if isinstance(value, datetime) else value
            for value in raw
        ])
    return rows


# ── acceptance harness ──────────────────────────────────────────────────────

def _svc() -> XlsxImportService:
    # The unified flow writes through the session/ORM; since the single-sheet
    # API removal the only service dependency is the (unused here) image store.
    return XlsxImportService()


async def _count(session, model) -> int:
    return (await session.execute(select(func.count()).select_from(model))).scalar()


async def _edge_count(session, table) -> int:
    return (await session.execute(select(func.count()).select_from(table))).scalar()


async def _one(session, model, **filters):
    stmt = select(model)
    for attr, value in filters.items():
        stmt = stmt.where(getattr(model, attr) == value)
    return (await session.execute(stmt)).scalars().one()


async def seed_world(session):
    """Pre-import game state: the org «гильдия копья» (case-varied against
    the file, with backstory/end_date to preserve) and type «война»."""
    desc = DescriptionModel(characteristics="", backstory="Древний устав цеха")
    session.add(desc)
    await session.flush()
    org = OrganizationModel(
        name="гильдия копья", start_date=date(1140, 1, 1),
        end_date=date(1199, 12, 31), description_id=desc.id,
    )
    war = EventTypeModel(name="война", color_index=3, sort_order=0)
    session.add_all([org, war])
    await session.flush()
    return org, war


# ── fixture drift guard: the committed binary == the generator ─────────────

class TestFixtureGenerator:
    def test_resource_exists(self):
        assert FIXTURE_PATH.is_file()

    def test_committed_fixture_matches_generator_cell_for_cell(self, tmp_path):
        regrown = tmp_path / "regrown.xlsx"
        build_import_sample_workbook().save(regrown)
        committed = load_workbook(FIXTURE_PATH, read_only=True)
        fresh = load_workbook(regrown, read_only=True)
        try:
            assert committed.sheetnames == fresh.sheetnames
            for title in fresh.sheetnames:
                assert _sheet_values(committed, title) == _sheet_values(fresh, title)
        finally:
            committed.close()
            fresh.close()

    def test_deliberate_problem_rows_keep_their_row_numbers(self):
        # The pre-analysis expectations below pin Excel row numbers — a
        # silently reordered FIXTURE_ROWS must break here first.
        wb = load_workbook(FIXTURE_PATH, read_only=True)
        try:
            events = _sheet_values(wb, "События")
            assert events[3][0] == "Пир в ратуше"
            assert events[3][1] == "31.12.2025"
            chars = _sheet_values(wb, "Персонажи")
            assert chars[5][0] == "Гоблин-наёмник"
        finally:
            wb.close()


# ── 6.1 — pre-analysis of the fixture (spec «Пред-анализ», upsert, ghosts) ─

class TestPreAnalysis:
    async def test_clean_file_parts_have_no_fatals_or_warnings(self, async_session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        assert not plan.has_fatal
        assert plan.fatal_errors == [] and plan.warnings == []

    async def test_problem_rows_are_planned_skips_with_positions(self, async_session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        assert [
            (i.sheet, i.row_number, i.reason) for i in plan.skipped_rows
        ] == EXPECTED_SKIPS

    async def test_in_file_merge_combines_the_two_blacksmith_rows(self, async_session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        rows = [r for r in plan.planned_rows if r.entity_type == "character"]
        assert len(rows) == 3  # Иван, Марта, merged «Старый Кузнец»
        merged = plan.lookup_row("character", "Старый Кузнец")
        assert merged.first_row_number == 4
        # later non-empty overrides, empty cells keep the earlier value
        assert merged.fields["start_date"] == MonthDay(1161, 2, 2)
        assert merged.fields["characteristics"] == "Молчалив, знает все ходы"
        assert merged.fields["backstory"] == "Бывший капитан городской стражи"
        assert merged.fields["rating"] == 3
        # links accumulate across the merged rows, first-seen order
        assert [r.name for r in merged.links["event"]] == [
            "Взятие Штурмграда", "Поход каравана на восток",
        ]

    async def test_link_columns_resolve_to_other_sheets_of_the_file(self, async_session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        ball = plan.lookup_row("event", "Взятие Штурмграда")
        # every `;`-segment names a row of another sheet → resolved to file
        for target_type in ("character", "organization", "item", "location"):
            for ref in ball.links[target_type]:
                if ref.name == "Амулет вдовы":
                    continue  # the deliberate ghost (test below)
                assert ref.resolution == LINK_TO_FILE
                assert plan.lookup_row(target_type, ref.name) is not None
        # and from the opposite side too (cross-sheet references both ways)
        ivan = plan.lookup_row("character", "Иван Ковач")
        assert [r.name for r in ivan.links["event"]] == [
            "Взятие Штурмграда", "Поход каравана на восток",
        ]

    async def test_ghost_target_spans_the_dates_of_its_referrers(self, async_session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        ghost = plan.ghosts[("item", "амулет вдовы")]
        # min start / max end из строк «Взятие…» (1200-05-01…1200-09-15) и
        # «Поход…» (1202-06-10…1203-01-20) — spec «Противоречивые даты»
        assert (ghost.min_start, ghost.max_end) == (
            MonthDay(1200, 5, 1), MonthDay(1203, 1, 20),
        )
        assert ghost.referenced_by == [("События", 2), ("События", 3)]
        # the same cell mixes a ghost with a file row → per-reference kind
        refs = plan.lookup_row("event", "Поход каравана на восток").links["item"]
        assert [r.resolution for r in refs] == [LINK_TO_FILE, LINK_TO_GHOST]

    async def test_unique_db_match_becomes_an_update_plan_of_nonempty_cells(
        self, async_session
    ):
        org, _ = await seed_world(async_session)
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        row = plan.lookup_row("organization", "Гильдия копья")
        # lower(name) uniqueness — the case-varied DB org is the update target
        assert row.is_update and row.existing_id == org.id
        # only non-empty cells reach the update (spec «Пустая ячейка не затирает»)
        assert row.fields["characteristics"] == "Наёмники и ремесленники старого города"
        assert "backstory" not in row.fields and "end_date" not in row.fields

    async def test_broken_rows_cast_no_shadow_on_the_plan(self, async_session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        assert plan.lookup_row("event", "Пир в ратуше") is None
        assert plan.lookup_row("character", "Гоблин-наёмник") is None


# ── 6.1 — applying the fixture (upsert, links, ghosts, one commit) ─────────

class TestApplyFixture:
    async def _apply(self, session):
        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(session))
        return plan, await _svc().apply_plan(plan, GameSessionUoW(session))

    async def test_imports_entities_ghost_and_links_into_an_empty_db(self, async_session):
        _plan, report = await self._apply(async_session)
        # 10 unique file rows + the ghost «Амулет вдовы»; nothing to update
        assert report.created == 11 and report.updated == 0
        assert report.links == 17
        assert [(i.sheet, i.row_number, i.reason) for i in report.skipped] == EXPECTED_SKIPS
        assert report.warnings == []

    async def test_every_sheet_landed_and_broken_rows_never_did(self, async_session):
        await self._apply(async_session)
        assert await _count(async_session, EventModel) == 2
        assert await _count(async_session, CharacterModel) == 3
        assert await _count(async_session, LocationModel) == 2
        assert await _count(async_session, OrganizationModel) == 1
        assert await _count(async_session, ItemModel) == 3  # + ghost
        events = (await async_session.execute(select(EventModel.name))).scalars().all()
        assert set(events) == {"Взятие Штурмграда", "Поход каравана на восток"}

    async def test_ghost_materializes_with_referrer_dates_and_decision(self, async_session):
        _plan, report = await self._apply(async_session)
        ghost = await _one(async_session, ItemModel, name="Амулет вдовы")
        assert (ghost.start_date, ghost.end_date) == (
            date(1200, 5, 1), date(1203, 1, 20),
        )
        ghost_decision = next(d for d in report.decisions if "Амулет вдовы" in d)
        assert "Автосоздание" in ghost_decision
        assert "лист «События», строка 2" in ghost_decision

    async def test_unknown_event_types_are_auto_created(self, async_session):
        _plan, report = await self._apply(async_session)
        names = {t.name for t in (
            await async_session.execute(select(EventTypeModel))
        ).scalars().all()}
        assert names == {"Война", "Поход"}
        assert (await _one(async_session, EventTypeModel, name="Война")).color_index == 1
        assert (await _one(async_session, EventTypeModel, name="Поход")).color_index == 2
        ball = await _one(async_session, EventModel, name="Взятие Штурмграда")
        assert ball.event_type.name == "Война"
        # two new types + the ghost — each automatic decision is reported
        assert len(report.decisions) == 3

    async def test_links_install_over_every_involved_association_table(self, async_session):
        await self._apply(async_session)
        # 17 distinct edges from FIXTURE_ROWS, deduplicated across sheets
        assert (await _edge_count(async_session, models.event_character)) == 5
        assert (await _edge_count(async_session, models.event_organization)) == 1
        assert (await _edge_count(async_session, models.event_item)) == 4
        assert (await _edge_count(async_session, models.event_location)) == 2
        assert (await _edge_count(async_session, models.character_item)) == 2
        assert (await _edge_count(async_session, models.character_location)) == 2
        assert (await _edge_count(async_session, models.organization_character)) == 1

        ball = await _one(async_session, EventModel, name="Взятие Штурмграда")
        assert {c.name for c in ball.characters} == {"Иван Ковач", "Марта", "Старый Кузнец"}
        assert {i.name for i in ball.items} == {"Штурмовой щит", "Амулет вдовы"}
        assert {o.name for o in ball.organizations} == {"Гильдия копья"}
        assert {loc.name for loc in ball.locations} == {"Штурмград"}
        ivan = await _one(async_session, CharacterModel, name="Иван Ковач")
        assert {e.name for e in ivan.events} == {
            "Взятие Штурмграда", "Поход каравана на восток",
        }
        assert {i.name for i in ivan.items} == {"Штурмовой щит", "Карта востока"}

    async def test_merged_row_lands_as_one_entity_with_both_links(self, async_session):
        await self._apply(async_session)
        smiths = (await async_session.execute(
            select(CharacterModel).where(func.lower(CharacterModel.name) == "старый кузнец")
        )).scalars().all()
        assert len(smiths) == 1
        smith = smiths[0]
        assert smith.start_date == date(1161, 2, 2)
        assert smith.description.characteristics == "Молчалив, знает все ходы"
        assert smith.description.backstory == "Бывший капитан городской стражи"
        assert smith.rating == 3
        assert {e.name for e in smith.events} == {
            "Взятие Штурмграда", "Поход каравана на восток",
        }

    async def test_upsert_preserves_cells_the_row_left_empty(self, async_session):
        org, _ = await seed_world(async_session)
        _plan, report = await self._apply(async_session)
        assert report.updated == 1 and report.created == 10  # org updated, ghost created
        await async_session.refresh(org)
        assert org.name == "гильдия копья"          # upsert never renames (D7)
        assert org.start_date == date(1150, 1, 1)   # non-empty cell overwrote
        assert org.description.characteristics == "Наёмники и ремесленники старого города"
        # the row left Предыстория/Дата конца empty — both survive untouched
        assert org.description.backstory == "Древний устав цеха"
        assert org.end_date == date(1199, 12, 31)

    async def test_seeded_event_type_is_reused_not_duplicated(self, async_session):
        _, war = await seed_world(async_session)
        _plan, report = await self._apply(async_session)
        assert await _count(async_session, EventTypeModel) == 2  # «война» + «Поход»
        ball = await _one(async_session, EventModel, name="Взятие Штурмграда")
        assert ball.event_type_id == war.id  # lower() reuse, no second «Война»
        # decisions: only the new type + the ghost (the reused type is silent)
        assert len(report.decisions) == 2

    async def test_reimport_updates_everything_and_links_nothing_new(self, async_session):
        await self._apply(async_session)
        _plan, second = await self._apply(async_session)
        # every file row now matches its unique DB namesake → pure updates
        assert second.created == 0 and second.updated == 10
        assert second.links == 0            # add-only pass: all edges already exist
        assert second.decisions == []
        assert [(i.sheet, i.row_number) for i in second.skipped] == [
            ("События", 4), ("Персонажи", 6),
        ]
        assert (await _edge_count(async_session, models.event_character)) == 5
        assert await _count(async_session, CharacterModel) == 3


# ── add-era-aware-dates 5.2 — BC dates through ghosts and planned rows ─────

class TestApplyEraAware:
    async def test_ghost_autocreates_from_a_bc_referring_row(self, tmp_path, async_session):
        # A row with signed-ISO/text BC dates links an unknown item: the ghost
        # materializes with the same era pair (bounds compared by era key),
        # and both entities persist era flags + chronology keys derived by the
        # ORM hook — the same single persistence path as any other row.
        wb = Workbook()
        wb.remove(wb.active)
        ws = wb.create_sheet("События")
        ws.append(["Имя", "Дата начала", "Дата конца", "Связь предметами"])
        ws.append(["Угощение Юлии", "-0044-03-15", "5 марта 43 г. до н.э.", "Амфора"])
        path = tmp_path / "bc_ghost.xlsx"
        wb.save(path)

        plan = await _svc().analyze_file(path, GameSessionUoW(async_session))
        ghost_plan = plan.ghosts[("item", "амфора")]
        assert (ghost_plan.min_start, ghost_plan.min_start_bc) == (MonthDay(44, 3, 15), True)
        assert (ghost_plan.max_end, ghost_plan.max_end_bc) == (MonthDay(43, 3, 5), True)

        report = await _svc().apply_plan(plan, GameSessionUoW(async_session))

        event = await _one(async_session, EventModel, name="Угощение Юлии")
        assert (event.start_date, bool(event.start_bc)) == (date(44, 3, 15), True)
        assert (event.end_date, bool(event.end_bc)) == (date(43, 3, 5), True)
        assert event.start_key == era_key(date(44, 3, 15), True)
        assert event.end_key == era_key(date(43, 3, 5), True)

        ghost = await _one(async_session, ItemModel, name="Амфора")
        assert (ghost.start_date, bool(ghost.start_bc)) == (date(44, 3, 15), True)
        assert (ghost.end_date, bool(ghost.end_bc)) == (date(43, 3, 5), True)
        assert ghost.start_key < 0 < era_key(date(1, 1, 1), False)
        assert [i.id for i in event.items] == [ghost.id]
        assert any(i.id == event.id for i in ghost.events)

        decision = next(d for d in report.decisions if "Амфора" in d)
        assert "Автосоздание" in decision and "до н.э." in decision


# ── C5 task 2.4 — the subject caption of a refused custom-branch date ──────

# A game calendar of the delta-spec vocabulary: «Зимостой» (30 days), the
# intercalary «Медожор», no «Флорель» anywhere.  Row problems are only ever
# produced by the custom grammar, so the whole class runs on this calendar.
_CUSTOM_SPEC = game_calendar.CalendarSpec(
    months=(
        game_calendar.MonthSpec("Зимостой", 30),
        game_calendar.MonthSpec("Ледокол", 15),
    ),
    week_names=("пн", "вт", "ср", "чт", "пт", "сб", "вс"),
    intercalary=(game_calendar.IntercalarySpec("Медожор", after_month=1),),
)
_CUSTOM = game_calendar.CustomCalendar(_CUSTOM_SPEC)


class TestDateProblemReasons:
    # Spec «Колонки листа»: a custom-branch form the grammar recognized but
    # refuses surfaces as a planned skip whose caption names the subject —
    # the display texts live in the service, not in the pure parser (D4).
    @pytest.mark.parametrize(("cell", "reason"), [
        ("3 Флорель 44", "дата начала: месяц «Флорель» не найден в календаре игры"),
        ("3 Медожор 44", "дата начала: у вставного дня «Медожор» не бывает номера дня"),
        ("Зимостой 44", "дата начала: месяц «Зимостой» без номера дня"),
        ("3 Зимостой 0", "дата начала: число «0» вне границ игрового календаря"),
        ("44 г. до н.э.", "дата начала: значение «44 г. до н.э.» не является датой"),
    ])
    async def test_every_refused_date_names_its_subject(self, tmp_path, cell, reason):
        wb = Workbook()
        wb.remove(wb.active)
        ws = wb.create_sheet("Персонажи")
        ws.append(["Имя", "Дата начала"])
        ws.append(["Стражник", cell])
        path = tmp_path / "problems.xlsx"
        wb.save(path)

        game_calendar.set_current_calendar(_CUSTOM)
        try:
            plan = await _svc().analyze_file(path)
        finally:
            game_calendar.reset_current_calendar()
        assert [(i.sheet, i.row_number, i.reason) for i in plan.skipped_rows] == [
            ("Персонажи", 2, reason)
        ]
        assert plan.planned_rows == []

    async def test_game_form_row_imports_with_the_calendar_coordinate(self, tmp_path):
        wb = Workbook()
        wb.remove(wb.active)
        ws = wb.create_sheet("Персонажи")
        ws.append(["Имя", "Дата начала"])
        ws.append(["Зимовик", "3 Зимостой 44"])
        path = tmp_path / "game_form.xlsx"
        wb.save(path)

        game_calendar.set_current_calendar(_CUSTOM)
        try:
            plan = await _svc().analyze_file(path)
        finally:
            game_calendar.reset_current_calendar()
        assert not plan.skipped_rows
        row = plan.lookup_row("character", "Зимовик")
        assert row.fields["start_date"] == game_calendar.MonthDay(44, 1, 3)
        assert row.fields.get("start_bc") is False

    async def test_refused_optional_end_date_never_skips_the_row(self, tmp_path):
        # The optional «Дата конца» keeps its carried contract (spec: only the
        # start date is a row problem) — a refused game form there simply
        # leaves the slot unapplied, exactly like unparsable garbage did.
        wb = Workbook()
        wb.remove(wb.active)
        ws = wb.create_sheet("Персонажи")
        ws.append(["Имя", "Дата начала", "Дата конца"])
        ws.append(["Долгострой", "2026-01-05", "3 Медожор 44"])
        path = tmp_path / "end_problem.xlsx"
        wb.save(path)

        game_calendar.set_current_calendar(_CUSTOM)
        try:
            plan = await _svc().analyze_file(path)
        finally:
            game_calendar.reset_current_calendar()
        assert not plan.skipped_rows
        row = plan.lookup_row("character", "Долгострой")
        assert "end_date" not in row.fields

    async def test_preset_caption_is_untouched_by_the_problem_channel(self, tmp_path):
        # The preset branch never fills DateParse.problem (D5): its skip
        # caption stays the carried "не является датой" wording verbatim.
        wb = Workbook()
        wb.remove(wb.active)
        ws = wb.create_sheet("Персонажи")
        ws.append(["Имя", "Дата начала"])
        ws.append(["Обычный", "3 Зимостой 44"])
        path = tmp_path / "preset_refusal.xlsx"
        wb.save(path)

        plan = await _svc().analyze_file(path)
        assert [i.reason for i in plan.skipped_rows] == [
            "дата начала: значение «3 Зимостой 44» не является датой"
        ]


# ── 6.1 — transaction (spec «Транзакционность импорта») ────────────────────

class TestTransaction:
    async def test_success_commits_exactly_once(self, async_session, monkeypatch):
        # The unit of work holds the finish (task 5.11): count the commits and
        # rollbacks on the session the unit runs over — the removed
        # commit/rollback callback parameters spied on exactly this.
        commits, rollbacks = [], []
        real_commit, real_rollback = async_session.commit, async_session.rollback

        async def spy_commit():
            commits.append(True)
            await real_commit()

        async def spy_rollback():
            rollbacks.append(True)
            await real_rollback()

        monkeypatch.setattr(async_session, "commit", spy_commit)
        monkeypatch.setattr(async_session, "rollback", spy_rollback)

        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        report = await _svc().apply_plan(plan, GameSessionUoW(async_session))
        assert (report.created, report.links) == (11, 17)
        assert commits == [True] and rollbacks == []

    async def test_failure_mid_pass_2_rolls_the_whole_import_back(
        self, async_session, monkeypatch
    ):
        org, _ = await seed_world(async_session)
        await async_session.commit()
        commits, rollbacks = [], []
        real_commit, real_rollback = async_session.commit, async_session.rollback

        async def spy_commit():
            commits.append(True)
            await real_commit()

        async def spy_rollback():
            rollbacks.append(True)
            await real_rollback()

        monkeypatch.setattr(async_session, "commit", spy_commit)
        monkeypatch.setattr(async_session, "rollback", spy_rollback)

        svc = _svc()

        async def boom(ref, instances, session):
            raise RuntimeError("технический сбой прохода 2")

        monkeypatch.setattr(svc, "_resolve_link_target", boom)

        plan = await _svc().analyze_file(FIXTURE_PATH, GameSessionUoW(async_session))
        with pytest.raises(RuntimeError, match="сбой"):
            await svc.apply_plan(plan, GameSessionUoW(async_session))

        assert commits == [] and rollbacks == [True]
        # nothing of the import survives — the DB stays as it was before it
        assert await _count(async_session, EventModel) == 0
        assert await _count(async_session, CharacterModel) == 0
        assert await _count(async_session, ItemModel) == 0
        assert await _count(async_session, EventTypeModel) == 1
        await async_session.refresh(org)
        assert org.description.backstory == "Древний устав цеха"
