"""Five-sheet import template (task group 5, rework-xlsx-import).

The committed binary ``resources/import_template.xlsx`` is generated by
:func:`build_template_workbook` below — the single reproducible source of the
template (5.1): headers come from the schema registry (never hand-typed), the
sample rows are the ``SAMPLE_ROWS`` data. The first tests pin the committed
file against this generator (it must match cell-for-cell), the rest prove the
contract on the committed resource itself: ``analyze_file`` yields zero
problems (no fatal, no warnings, no planned skips, and — with a clean DB —
no ghosts), and ``apply_plan`` into an empty DB imports every entity plus the
cross-sheet ``;`` links.
"""
from __future__ import annotations

from datetime import date, datetime
from pathlib import Path

from openpyxl import Workbook, load_workbook
from sqlalchemy import select

from app.application.services import xlsx_schema
from app.application.services.xlsx_import_service import XlsxImportService
from app.infrastructure.db.models import (
    CharacterModel,
    EventModel,
    ItemModel,
    LocationModel,
    OrganizationModel,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_PATH = REPO_ROOT / "resources" / "import_template.xlsx"

# Sample rows keyed by column key (ColumnSpec.key) / link target type. The
# rows cross-reference each other in BOTH directions with `;` lists (spec
# «Ссылка на строку другого листа») so the template demonstrates the link
# syntax; «Бал» carries a native date cell, the other rows ISO text — the
# two accepted date forms.
SAMPLE_ROWS: dict[str, list[dict[str, object]]] = {
    "event": [
        {
            "name": "Бал", "start_date": date(1820, 5, 1), "end_date": "1820-05-02",
            "characteristics": "Зимний бал в особняке на соборной площади",
            "backstory": "Танец, после которого старый город заговорил о Марии и Иване.",
            "rating": 4, "event_type": "Праздник",
            "character": "Иван; Мария", "organization": "Городская управа",
            "item": "Дневник", "location": "Особняк",
        },
        {
            "name": "Дуэль", "start_date": "1815-01-10", "end_date": None,
            "characteristics": "На рассвете, за старыми дубами",
            "backstory": None, "rating": None, "event_type": "Дуэль",
            "character": "Иван", "organization": None,
            "item": None, "location": "Поляна",
        },
    ],
    "character": [
        {
            "name": "Иван", "start_date": "1790-03-15", "end_date": None,
            "characteristics": "Городской кузнец",
            "backstory": "Учился ремеслу у отца, клялся отомстить за него.",
            "rating": 5, "personality": "Вспыльчивый", "tasks": "Починить крышу кузницы",
            "music_url": "https://example.org/tema-ivana.mp3", "image": None,
            "event": "Бал; Дуэль", "organization": None, "item": None,
            "location": "Особняк",
        },
        {
            "name": "Мария", "start_date": "1795-07-20", "end_date": None,
            "characteristics": "Приёмная дочь банкира",
            "backstory": "Ведёт дневник, который не для посторонних глаз.",
            "rating": None, "personality": "Сдержанная", "tasks": None,
            "music_url": None, "image": None,
            "event": "Бал", "organization": "Городская управа",
            "item": "Дневник", "location": "Особняк",
        },
    ],
    "location": [
        {
            "name": "Особняк", "start_date": "1800-01-01", "end_date": None,
            "characteristics": "Каменный особняк на соборной площади",
            "backstory": None, "rating": None, "tasks": "Ремонт восточного крыла",
            "music_url": None, "image": None,
            "event": "Бал", "character": "Иван; Мария", "organization": None,
            "item": None,
        },
        {
            "name": "Поляна", "start_date": "1815-01-10", "end_date": None,
            "characteristics": "Поляна за старыми дубами",
            "backstory": None, "rating": None, "tasks": None,
            "music_url": None, "image": None,
            "event": "Дуэль", "character": None, "organization": None,
            "item": None,
        },
    ],
    "organization": [
        {
            "name": "Городская управа", "start_date": "1780-02-01", "end_date": None,
            "characteristics": "Магистрат старого города",
            "backstory": None, "rating": None, "tasks": "Благоустройство площади",
            "music_url": None, "image": None,
            "event": "Бал", "character": "Мария", "item": None, "location": None,
        },
    ],
    "item": [
        {
            "name": "Дневник", "start_date": "1819-12-31", "end_date": None,
            "characteristics": "Кожаный дневник с вензелями",
            "backstory": None, "rating": None, "music_url": None,
            "event": "Бал", "character": "Мария", "organization": None,
            "location": None,
        },
    ],
}


def template_headers(sheet: xlsx_schema.SheetSpec) -> list[str]:
    """RU headers of one sheet — straight from the registry (all_headers)."""
    return [column.label for column in xlsx_schema.all_headers(sheet)]


def template_row_values(
    sheet: xlsx_schema.SheetSpec, row: dict[str, object]
) -> list[object]:
    """Sample-row values ordered exactly like ``template_headers``.

    A scalar column is looked up by its ``key``, a link column by its target
    type — the two namespaces never collide (column keys are field names,
    link keys are entity types).
    """
    return [
        row.get(
            column.key if isinstance(column, xlsx_schema.ColumnSpec)
            else column.target_type
        )
        for column in xlsx_schema.all_headers(sheet)
    ]


def build_template_workbook() -> Workbook:
    """Regenerate the template workbook from the registry + SAMPLE_ROWS."""
    wb = Workbook()
    wb.remove(wb.active)
    for sheet in xlsx_schema.all_sheets():
        ws = wb.create_sheet(sheet.sheet_name)
        ws.append(template_headers(sheet))
        for row in SAMPLE_ROWS[sheet.entity_type]:
            ws.append(template_row_values(sheet, row))
    return wb


def _sheet_values(wb: Workbook, title: str) -> list[list[object]]:
    """Cell values of one sheet with datetimes normalized to dates."""
    rows = []
    for raw in wb[title].iter_rows(values_only=True):
        rows.append([
            value.date() if isinstance(value, datetime) else value
            for value in raw
        ])
    return rows


# ── 5.1 — the committed resource matches the registry-generated template ──

class TestCommittedTemplate:
    def test_resource_exists(self):
        assert TEMPLATE_PATH.is_file()

    def test_committed_file_matches_generator_cell_for_cell(self, tmp_path):
        # Generation reproducibility lives HERE: regenerating the workbook
        # from the registry (headers) + SAMPLE_ROWS (data) must reproduce the
        # committed binary's values exactly — a registry drift breaks this.
        regenerated = tmp_path / "regenerated.xlsx"
        build_template_workbook().save(regenerated)
        committed = load_workbook(TEMPLATE_PATH, read_only=True)
        fresh = load_workbook(regenerated, read_only=True)
        try:
            assert committed.sheetnames == fresh.sheetnames
            for title in fresh.sheetnames:
                assert _sheet_values(committed, title) == _sheet_values(fresh, title)
        finally:
            committed.close()
            fresh.close()

    def test_headers_are_full_ru_registry_headers(self):
        wb = load_workbook(TEMPLATE_PATH, read_only=True)
        try:
            for sheet in xlsx_schema.all_sheets():
                headers = _sheet_values(wb, sheet.sheet_name)[0]
                assert headers == template_headers(sheet)
                # every sheet carries its four link columns (spec «Колонки связей»)
                link_labels = {c.label for c in sheet.link_columns}
                assert link_labels <= set(headers)
                assert len(sheet.link_columns) == 4
        finally:
            wb.close()


# ── 5.1 — zero problems on analyze + clean import into an empty DB ────────

def _svc() -> XlsxImportService:
    # apply_plan writes through the session/ORM: the service has no other
    # dependency than the (here unused) image store since group 6 cleanup.
    return XlsxImportService(image_store=None)


async def _names(session, model) -> set[str]:
    return {n for (n,) in (await session.execute(select(model.name))).all()}


class TestTemplateAnalyzeAndImport:
    async def test_analyzes_with_zero_problems(self, async_session):
        plan = await _svc().analyze_file(TEMPLATE_PATH, async_session)
        assert plan.fatal_errors == []
        assert plan.skipped_rows == []
        assert plan.warnings == []
        # Clean DB + full cross-references in the file itself → no ghosts.
        assert plan.ghosts == {}
        assert not plan.has_fatal

    async def test_imports_cleanly_into_empty_db(self, async_session):
        plan = await _svc().analyze_file(TEMPLATE_PATH, async_session)
        report = await _svc().apply_plan(plan, async_session)

        expected_entities = sum(len(rows) for rows in SAMPLE_ROWS.values())
        assert report.created == expected_entities  # every sample row is unique
        assert report.updated == 0
        assert report.skipped == []
        assert report.warnings == []
        assert await _names(async_session, EventModel) == {"Бал", "Дуэль"}
        assert await _names(async_session, CharacterModel) == {"Иван", "Мария"}
        assert await _names(async_session, LocationModel) == {"Особняк", "Поляна"}
        assert await _names(async_session, OrganizationModel) == {"Городская управа"}
        assert await _names(async_session, ItemModel) == {"Дневник"}

    async def test_link_columns_install_cross_sheet_links(self, async_session):
        plan = await _svc().analyze_file(TEMPLATE_PATH, async_session)
        report = await _svc().apply_plan(plan, async_session)

        # 11 distinct edges over the importable M2M tables; the samples
        # repeat edges from the opposite sheet on purpose (dedup).
        assert report.links == 11
        ball = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Бал")
        )).scalars().one()
        duel = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Дуэль")
        )).scalars().one()
        assert {c.name for c in ball.characters} == {"Иван", "Мария"}
        assert {e.name for e in duel.characters} == {"Иван"}
        assert {o.name for o in ball.organizations} == {"Городская управа"}
        assert {i.name for i in ball.items} == {"Дневник"}
        assert {loc.name for loc in ball.locations} == {"Особняк"}
        # cross-sheet direction from the other side:
        assert {e.name for e in duel.locations} == {"Поляна"}
        mansion = (await async_session.execute(
            select(LocationModel).where(LocationModel.name == "Особняк")
        )).scalars().one()
        assert {c.name for c in mansion.characters} == {"Иван", "Мария"}
        diary = (await async_session.execute(
            select(ItemModel).where(ItemModel.name == "Дневник")
        )).scalars().one()
        assert {c.name for c in diary.characters} == {"Мария"}

    async def test_scalar_and_date_and_rating_columns_land(self, async_session):
        plan = await _svc().analyze_file(TEMPLATE_PATH, async_session)
        await _svc().apply_plan(plan, async_session)

        ball = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Бал")
        )).scalars().one()
        # native Excel date cell + ISO-text end date both parsed; event type
        # auto-created (empty DB) and reaches the event.
        assert ball.start_date == date(1820, 5, 1)
        assert ball.end_date == date(1820, 5, 2)
        assert ball.event_type.name == "Праздник"
        ivan = (await async_session.execute(
            select(CharacterModel).where(CharacterModel.name == "Иван")
        )).scalars().one()
        assert ivan.rating == 5
        assert ivan.personality == "Вспыльчивый"
        assert ivan.tasks == "Починить крышу кузницы"
        assert ivan.music_url == "https://example.org/tema-ivana.mp3"
        assert ivan.description.characteristics == "Городской кузнец"
        assert ivan.description.backstory.startswith("Учился ремеслу")

    async def test_event_type_autocreation_is_reported(self, async_session):
        plan = await _svc().analyze_file(TEMPLATE_PATH, async_session)
        report = await _svc().apply_plan(plan, async_session)
        assert len(report.decisions) == 2  # «Праздник» + «Дуэль»
        assert all("Автосоздание" in d for d in report.decisions)
