"""Five-sheet import template (rework-xlsx-import group 5, C5 group 3).

The committed binary ``resources/import_template.xlsx`` is generated by
:func:`app.application.services.xlsx_template.build_template_workbook` — the
single reproducible source of the template (5.1): headers come from the
schema registry (never hand-typed), the sample rows are its ``SAMPLE_ROWS``
data. The first tests pin the committed file against the generator (it must
match cell-for-cell) while the resource still exists; the rest prove the
contract on the generator's own output (under the «Стандартный» preset it is
cell-for-cell the committed file, so nothing is lost when piece C5 removes
the resource): ``analyze_file`` yields zero problems (no fatal, no warnings,
no planned skips, and — with a clean DB — no ghosts), and ``apply_plan`` into
an empty DB imports every entity plus the cross-sheet ``;`` links.
"""
from __future__ import annotations

from datetime import date, datetime
from pathlib import Path

import pytest
from openpyxl import Workbook, load_workbook
from sqlalchemy import select

from app.application.services import xlsx_schema
from app.application.services.xlsx_import_service import XlsxImportService
from app.application.services.xlsx_template import (
    SAMPLE_ROWS,
    build_template_workbook,
    template_headers,
)
from app.domain.game_calendar import StandardCalendar
from app.infrastructure.db.uow import GameSessionUoW
from app.infrastructure.db.models import (
    CharacterModel,
    EventModel,
    ItemModel,
    LocationModel,
    OrganizationModel,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_PATH = REPO_ROOT / "resources" / "import_template.xlsx"

# The template the committed file reproduces is the preset's template — the
# generator's calendar argument (C5) is explicit.
_STANDARD = StandardCalendar()

# Piece C5 group 4 removes the static resource once the dialog generates the
# template itself; every resource-shaped test below then skips, while the
# generator-based contract (and the gold snapshots in
# test_xlsx_template_generator.py) keeps guarding the same cells.
requires_resource = pytest.mark.skipif(
    not TEMPLATE_PATH.is_file(),
    reason="static resources/import_template.xlsx removed (C5 group 4)",
)


def _generated_template(tmp_path: Path):
    """Save the preset-generated template workbook and return its path."""
    path = tmp_path / "template.xlsx"
    build_template_workbook(_STANDARD).save(path)
    return path



def _sheet_values(wb: Workbook, title: str) -> list[list[object]]:
    """Cell values of one sheet with datetimes normalized to dates."""
    rows = []
    for raw in wb[title].iter_rows(values_only=True):
        rows.append([
            value.date() if isinstance(value, datetime) else value
            for value in raw
        ])
    return rows


# ── 5.1 — the committed resource matches the registry-generated template ──

@requires_resource
class TestCommittedTemplate:
    def test_resource_exists(self):
        assert TEMPLATE_PATH.is_file()

    def test_committed_file_matches_generator_cell_for_cell(self, tmp_path):
        # Generation reproducibility lives HERE: regenerating the workbook
        # from the registry (headers) + SAMPLE_ROWS (data) must reproduce the
        # committed binary's values exactly — a registry drift breaks this.
        regenerated = tmp_path / "regenerated.xlsx"
        build_template_workbook(_STANDARD).save(regenerated)
        committed = load_workbook(TEMPLATE_PATH, read_only=True)
        fresh = load_workbook(regenerated, read_only=True)
        try:
            assert committed.sheetnames == fresh.sheetnames
            for title in fresh.sheetnames:
                assert _sheet_values(committed, title) == _sheet_values(fresh, title)
        finally:
            committed.close()
            fresh.close()

    def test_headers_are_full_ru_registry_headers(self):
        wb = load_workbook(TEMPLATE_PATH, read_only=True)
        try:
            for sheet in xlsx_schema.all_sheets():
                headers = _sheet_values(wb, sheet.sheet_name)[0]
                assert headers == template_headers(sheet)
                # every sheet carries its four link columns (spec «Колонки связей»)
                link_labels = {c.label for c in sheet.link_columns}
                assert link_labels <= set(headers)
                assert len(sheet.link_columns) == 4
        finally:
            wb.close()


# ── 5.1 — zero problems on analyze + clean import into an empty DB ────────

def _svc() -> XlsxImportService:
    # apply_plan writes through the session/ORM: the service has no other
    # dependency than the (here unused) image store since group 6 cleanup.
    return XlsxImportService(image_store=None)


async def _names(session, model) -> set[str]:
    return {n for (n,) in (await session.execute(select(model.name))).all()}


class TestTemplateAnalyzeAndImport:
    async def test_analyzes_with_zero_problems(self, tmp_path, async_session):
        plan = await _svc().analyze_file(_generated_template(tmp_path), GameSessionUoW(async_session))
        assert plan.fatal_errors == []
        assert plan.skipped_rows == []
        assert plan.warnings == []
        # Clean DB + full cross-references in the file itself → no ghosts.
        assert plan.ghosts == {}
        assert not plan.has_fatal

    async def test_imports_cleanly_into_empty_db(self, tmp_path, async_session):
        plan = await _svc().analyze_file(_generated_template(tmp_path), GameSessionUoW(async_session))
        report = await _svc().apply_plan(plan, GameSessionUoW(async_session))

        expected_entities = sum(len(rows) for rows in SAMPLE_ROWS.values())
        assert report.created == expected_entities  # every sample row is unique
        assert report.updated == 0
        assert report.skipped == []
        assert report.warnings == []
        assert await _names(async_session, EventModel) == {"Бал", "Дуэль", "Заговор"}
        assert await _names(async_session, CharacterModel) == {"Иван", "Мария"}
        assert await _names(async_session, LocationModel) == {"Особняк", "Поляна"}
        assert await _names(async_session, OrganizationModel) == {"Городская управа"}
        assert await _names(async_session, ItemModel) == {"Дневник"}

    async def test_link_columns_install_cross_sheet_links(self, tmp_path, async_session):
        plan = await _svc().analyze_file(_generated_template(tmp_path), GameSessionUoW(async_session))
        report = await _svc().apply_plan(plan, GameSessionUoW(async_session))

        # 11 distinct edges over the importable M2M tables; the samples
        # repeat edges from the opposite sheet on purpose (dedup).
        assert report.links == 11
        ball = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Бал")
        )).scalars().one()
        duel = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Дуэль")
        )).scalars().one()
        assert {c.name for c in ball.characters} == {"Иван", "Мария"}
        assert {e.name for e in duel.characters} == {"Иван"}
        assert {o.name for o in ball.organizations} == {"Городская управа"}
        assert {i.name for i in ball.items} == {"Дневник"}
        assert {loc.name for loc in ball.locations} == {"Особняк"}
        # cross-sheet direction from the other side:
        assert {e.name for e in duel.locations} == {"Поляна"}
        mansion = (await async_session.execute(
            select(LocationModel).where(LocationModel.name == "Особняк")
        )).scalars().one()
        assert {c.name for c in mansion.characters} == {"Иван", "Мария"}
        diary = (await async_session.execute(
            select(ItemModel).where(ItemModel.name == "Дневник")
        )).scalars().one()
        assert {c.name for c in diary.characters} == {"Мария"}

    async def test_scalar_and_date_and_rating_columns_land(self, tmp_path, async_session):
        plan = await _svc().analyze_file(_generated_template(tmp_path), GameSessionUoW(async_session))
        await _svc().apply_plan(plan, GameSessionUoW(async_session))

        ball = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Бал")
        )).scalars().one()
        # native Excel date cell + ISO-text end date both parsed; event type
        # auto-created (empty DB) and reaches the event.
        assert ball.start_date == date(1820, 5, 1)
        assert ball.end_date == date(1820, 5, 2)
        assert ball.event_type.name == "Праздник"
        ivan = (await async_session.execute(
            select(CharacterModel).where(CharacterModel.name == "Иван")
        )).scalars().one()
        assert ivan.rating == 5
        assert ivan.personality == "Вспыльчивый"
        assert ivan.tasks == "Починить крышу кузницы"
        assert ivan.music_url == "https://example.org/tema-ivana.mp3"
        assert ivan.description.characteristics == "Городской кузнец"
        assert ivan.description.backstory.startswith("Учился ремеслу")
        # BC sample row: both text forms land as one BC era pair of dates,
        # keys derived (negative BC side, strictly ordered).
        zagovor = (await async_session.execute(
            select(EventModel).where(EventModel.name == "Заговор")
        )).scalars().one()
        assert zagovor.start_date == date(44, 3, 15) and zagovor.start_bc
        assert zagovor.end_date == date(43, 3, 1) and zagovor.end_bc
        assert zagovor.start_key < zagovor.end_key < 0

    async def test_event_type_autocreation_is_reported(self, tmp_path, async_session):
        plan = await _svc().analyze_file(_generated_template(tmp_path), GameSessionUoW(async_session))
        report = await _svc().apply_plan(plan, GameSessionUoW(async_session))
        assert len(report.decisions) == 2  # «Праздник» + «Дуэль»
        assert all("Автосоздание" in d for d in report.decisions)
